### ISSUE TITLE
Generated vocal file is 2seconds longer in duration than the target file!

### ISSUE THREAD

**Issue by aadarshsingh191198** [ws-choi/ISMIR2020_U_Nets_SVS#3]

**Comment by ws-choi** [comment]
Hi @aadarshsingh191198 ,
it is because our model automatically appends zero pads to the end of the original mixture.
The processing unit of our model is not a sample-level but a chunk of fixed-length samples (about 3 seconds).

If the length of the separated audio track should be the same of the mixture's
then you can simply slice the output array as follows: ```output=output[:mixture.shape[0]]```

**Comment by aadarshsingh191198** [comment]
Realized it late. Thanks for the help though!!
